export const ACTIVITY_TYPE = {
  WORK_ACTIVITY: 'WORK_ACTIVITY',
  PAID_VOCATION: 'PAID_VOCATION',
  UNPAID_VOCATION: 'UNPAID_VOCATION',
  SICK_LEAVE: 'SICK_LEAVE',
} as const;

export type ActivityType = (typeof ACTIVITY_TYPE)[keyof typeof ACTIVITY_TYPE];
